services:
  app:
    build: .
    command: python -u app.py
    ports:
      - "667:5000"
    volumes:
      - ./src:/app
    links:
      - db
  db:
    image: mongo:latest
    hostname: mongodb_oep
    environment:
      - MONGO_INITDB_DATABASE=oep_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27018:27017